version: '3.8'

services:
  user-service:
    image: user-service:1.0
    ports:
      - "8081:8081"
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - messenger-network

  #  auth-service:
  #    image: auth-service:1.0
  #    ports:
  #      - "8082:8082"
  #    build:
  #      context: ./auth-service
  #      dockerfile: ./Dockerfile
  #    container_name: auth-service
  #    environment:
  #      SPRING_PROFILES_ACTIVE: docker
  #    networks:
  #      - messenger-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    restart: always
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgresql-keycloak:5432/keycloak
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_PROXY: none
      PROXY_ADDRESS_FORWARDING: true
    volumes:
      - ./realm/:/opt/keycloak/data/import
    depends_on:
      - postgresql-keycloak
    networks:
      - messenger-network

  postgresql-keycloak:
    image: postgres:16-alpine
    container_name: postgresql-keycloak
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./data/postgres/keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      PGDATA: /data/postgres
    networks:
      - messenger-network

  postgresql-user-service:
    image: postgres:16-alpine
    container_name: postgresql-user-service
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./data/postgres/user-service:/var/lib/postgresql/data
      - ./init/user-service-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      PGDATA: /data/postgres
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: bridge
