version: '3.8'

services:
  postgresql-keycloak:
    image: postgres:16-alpine
    container_name: postgresql-keycloak
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./data/postgres/keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      PGDATA: /data/postgres
    networks:
      - messenger

  keycloak:
    image: jboss/keycloak:16.1.1
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      JBOSS_LOG_MANAGER_ROOT_LOGGER: DEBUG
      DB_VENDOR: postgres
      DB_ADDR: postgresql-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    #      KEYCLOAK_IMPORT: /opt/jboss/keycloak/realms/spring-social-realm.json
    container_name: keycloak
    #    volumes:
    #      - ./realms/:/opt/jboss/keycloak/realms
    depends_on:
      - postgresql-keycloak
    networks:
      - messenger

networks:
  messenger:
    driver: bridge