version: '3.8'

services:
  postgresql-user-service:
    image: postgres:16-alpine
    container_name: postgresql-user-service
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql-jotrack
    networks:
      - messenger

networks:
  messenger:
    driver: bridge