version: '3.8'

services:
  user-service:
    image: user-service:1.0
    ports:
      - "8081:8081"
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgresql-user-service
    networks:
      - messenger-network

  #  auth-service:
  #    image: auth-service:1.0
  #    ports:
  #      - "8082:8082"
  #    build:
  #      context: ./auth-service
  #      dockerfile: ./Dockerfile
  #    container_name: auth-service
  #    environment:
  #      SPRING_PROFILES_ACTIVE: docker
  #    networks:
  #      - messenger-network

  postgresql-user-service:
    container_name: postgresql-user-service
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-service
    volumes:
      - ./data/postgres/users:/var/lib/postgresql/data
      - ./init/user-service-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: bridge
