version: '3.8'

services:
  user-service:
    image: user-service:1.0
    ports:
      - "8081:8081"
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    #    depends_on:
    #      - postgresql-user-service
    #      - discovery-service
    networks:
      - messenger-network

  keycloak:
    image: jboss/keycloak:16.1.1
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      JBOSS_LOG_MANAGER_ROOT_LOGGER: DEBUG
      DB_VENDOR: postgres
      DB_ADDR: postgresql-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/realms/messenger-realm.json
    container_name: keycloak
    volumes:
      - ./init/realms/:/opt/jboss/keycloak/realms
    depends_on:
      - postgresql-keycloak
    networks:
      - messenger-network

  postgresql-keycloak:
    image: postgres:16-alpine
    container_name: postgresql-keycloak
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./data/postgres/keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      PGDATA: /data/postgres
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: bridge
